/// Owner statement PDF (§M24: "PDF to M17").
import React from "react";
import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: "Helvetica" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 },
  brandBlock: { flex: 1, paddingRight: 16 },
  logo: { width: 56, height: 56, objectFit: "contain", marginBottom: 3 },
  brand: { fontSize: 15, marginBottom: 1 },
  contact: { color: "#666", fontSize: 8, marginBottom: 1 },
  h1: { fontSize: 16, marginBottom: 2 },
  sub: { color: "#555", marginBottom: 14 },
  table: { width: "100%" },
  row: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#ddd", paddingVertical: 5 },
  cell: { flex: 1 },
  cellRight: { flex: 1, textAlign: "right" },
  head: { color: "#666", fontSize: 9 },
  total: { flexDirection: "row", borderTopWidth: 1, borderTopColor: "#222", marginTop: 8, paddingTop: 8 },
  totalLabel: { flex: 1, fontSize: 12 },
  totalValue: { flex: 1, textAlign: "right", fontSize: 12 },
  badge: { marginTop: 14, paddingVertical: 4, paddingHorizontal: 8, backgroundColor: "#eee", alignSelf: "flex-start" },
  footer: { position: "absolute", bottom: 24, left: 32, right: 32, color: "#888", fontSize: 8 }
});

export interface StatementPdfData {
  code: string;
  month: string;
  status: string;
  orgName: string;
  orgLegalName?: string;
  orgAddress?: string;
  orgPhone?: string;
  orgEmail?: string;
  orgTaxId?: string;
  orgLogo?: string;
  propertyName: string;
  buildingName: string;
  ownerName: string;
  contractCode: string;
  model: string;
  collectedMinor: number;
  grossShareMinor: number;
  managementFeeMinor: number;
  passthroughMinor: number;
  ownerMaintenanceMinor: number;
  adjustmentsMinor: number;
  netMinor: number;
  paidVia?: string | null;
  paidAt?: string | null;
}

const money = (m: number) =>
  `${m < 0 ? "−" : ""}$${(Math.abs(m) / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function OwnerStatementPdf({ data }: { data: StatementPdfData }) {
  const lines: Array<[string, number]> = [
    [data.model === "FIXED_RENT" ? "Fixed master rent" : `Collected revenue × owner share`, data.grossShareMinor],
    ["Management fee", -data.managementFeeMinor],
    ["Pass-through expenses", -data.passthroughMinor],
    ["Owner-borne maintenance", -data.ownerMaintenanceMinor],
    ["Adjustments", data.adjustmentsMinor]
  ];
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerRow}>
          <View style={styles.brandBlock}>
            {data.orgLogo ? (
              // eslint-disable-next-line jsx-a11y/alt-text
              <Image src={data.orgLogo} style={styles.logo} />
            ) : null}
            <Text style={styles.brand}>{data.orgName}</Text>
            {data.orgLegalName ? <Text style={styles.contact}>{data.orgLegalName}</Text> : null}
            {data.orgAddress ? <Text style={styles.contact}>{data.orgAddress}</Text> : null}
            {data.orgPhone ? <Text style={styles.contact}>{data.orgPhone}</Text> : null}
            {data.orgEmail ? <Text style={styles.contact}>{data.orgEmail}</Text> : null}
            {data.orgTaxId ? <Text style={styles.contact}>Tax ID: {data.orgTaxId}</Text> : null}
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={styles.h1}>Owner Statement {data.code}</Text>
          </View>
        </View>
        <Text style={styles.sub}>
          {data.month} · {data.buildingName} ({data.propertyName}) · {data.ownerName} · contract {data.contractCode} ({data.model})
        </Text>
        {data.model !== "FIXED_RENT" ? (
          <Text style={styles.sub}>Collections confirmed in {data.month}: {money(data.collectedMinor)}</Text>
        ) : null}
        <View style={styles.table}>
          <View style={styles.row}>
            <Text style={[styles.cell, styles.head]}>Component</Text>
            <Text style={[styles.cellRight, styles.head]}>Amount</Text>
          </View>
          {lines.map(([label, v]) => (
            <View key={label} style={styles.row}>
              <Text style={styles.cell}>{label}</Text>
              <Text style={styles.cellRight}>{money(v)}</Text>
            </View>
          ))}
        </View>
        <View style={styles.total}>
          <Text style={styles.totalLabel}>Net payout</Text>
          <Text style={styles.totalValue}>{money(data.netMinor)}</Text>
        </View>
        <Text style={styles.badge}>Status: {data.status.toUpperCase()}{data.paidAt ? ` · paid ${data.paidAt.slice(0, 10)} via ${data.paidVia}` : ""}</Text>
        <Text style={styles.footer}>
          {data.orgName} — generated by RentManager. Amounts reconcile to the ledger (accrual DR 3900 / CR 2200 on approval;
          payout DR 2200 / CR cash|bank on payment).
        </Text>
      </Page>
    </Document>
  );
}
